            SELECT ORD-COMP
              ASSIGN TO RANDOM "F-ORD-COMP"
              ORGANIZATION IS INDEXED
              ACCESS MODE IS DYNAMIC
              RECORD KEY IS ORD-COMP-LLAVE
              ALTERNATE RECORD KEY IS
                  ORD-COMP-PROV-LLAVE = ORD-COMP-PROVE, ORD-COMP-ID
              ALTERNATE RECORD KEY IS
                  ORD-COMP-FEC-LLAVE = ORD-COMP-FECHA, ORD-COMP-ID
              ALTERNATE RECORD KEY IS
                  ORD-COMP-PEND-LLAVE = ORD-COMP-PEND, ORD-COMP-ID
              FILE STATUS IS FS-COMUN.
